### ISSUE TITLE
problem resize when click

### ISSUE THREAD

**Issue by majidjamhsidi** [hariprasanths/GoogleNewsStandAnimation-Android#2]
hi , when i use  "com.android.support:support-v4:+" for other repository , see problem in resize .
image attached 
![Untitled-2](https://user-images.githubusercontent.com/26843732/82095181-c431eb00-9713-11ea-9f0d-0dc511cfbb2a.jpg)

**Comment by hariprasanths** [comment]
Can u give more details as to how I can recreate this issue?
Is this happening on the example app on the repo?
If so, which Android API level are you testing this?

**Comment by majidjamhsidi** [comment]
Thank you for your reply .
 i want to use another repo with this ripo .  when add this items to dependencies your example ,i see problem : 

    implementation 'com.android.support:design:28.0.0'
    implementation "com.android.support:support-v4:+"

    //splash screen
    implementation 'com.github.ViksaaSkool:AwesomeSplash:v1.0.0'
 
    //inject font
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'

    //circle menu
    implementation 'com.github.imangazalievm:circlemenu:2.0.2'

**Comment by hariprasanths** [comment]
What do you mean by using another repo with this example?

You don't need to have the files from this repo in order to use this animation somewhere.

If you want to use this animation, use this as a library by adding this dependency:
implementation 'hari.allagi:allagi:0.1.0'

**Comment by majidjamhsidi** [comment]
i want use other repo for my project , for example splash screen to first page or indicator or  inject font or  .... . 
when i use other repo ,  give some message from android studio
 : you must insert 2 implementation in bottom for resolve 

implementation 'com.android.support:design:28.0.0'
implementation "com.android.support:support-v4:+"
 

when i added to two implementation top in my dependencies ، problem in resize given .

**Comment by hariprasanths** [comment]
Please do send the following information so that I can recreate this issue:

1) The complete error message from the Android studio before adding these 2
lines:
implementation 'com.android.support:design:28.0.0'
implementation "com.android.support:support-v4:+"

2) The Android API level on which the issue has been encountered.

3) All the dependencies you are using (from the dependencies section in the
build.gradle file).

**Comment by majidjamhsidi** [comment]
This is a complete project that has a problem : ( attached )
[motahari.zip](https://github.com/hariprasanths/GoogleNewsStandAnimation-Android/files/4639028/motahari.zip)

**Comment by hariprasanths** [comment]
The library has been updated with the fix, use the latest version:
implementation 'hari.allagi:allagi:0.1.1'

Also, the library is now using Androidx, so you might also have to migrate your project to Androidx.

Thank you for bringing this issue to my attention.

**Comment by majidjamhsidi** [comment]
well done , its working correctly :)))))))
